### ISSUE TITLE
Check if `target_arch = "wasm32"`

### ISSUE THREAD

**Issue by omni-viral** [Lokathor/gfx-backend-runtime#5]
And only use `gl` then

**Comment by omni-viral** [comment]
This is my `Cargo.toml`

 ```toml
gfx-hal = "0.2"
gfx-backend-empty = { version = "0.2.1", optional = true }
gfx-backend-gl = { version = "0.2.0", optional = true }

[target.'cfg(all(target_os = "windows", not(target_arch = "wasm32")))'.dependencies]
gfx-backend-dx12 = { version = "0.2.1", optional = true }

[target.'cfg(any(all(target_os = "windows", not(target_arch = "wasm32")), all(unix, not(any(target_os = "macos", target_os = "ios")))))'.dependencies]
gfx-backend-vulkan = { version = "0.2.3", optional = true }

[target.'cfg(any(all(target_os = "macos", not(target_arch = "wasn32"), all(target_arch = "aarch64", target_os = "ios"))))'.dependencies]
gfx-backend-metal = { version = "0.2.3", optional = true }
```
